name: Formatting

on:
  push: {}
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.7'
        cabal-version: '3.6.2.0'

    - name: Install ormolu format commit and push
      run: |
        mkdir -p "$HOME/.cabal/bin"
        cabal update
        cabal install --installdir="$HOME/.cabal/bin" --overwrite-policy=always ormolu
        $HOME/.cabal/bin/ormolu --mode inplace $(find . -name '*.hs')
        git config --global user.email "formatting@bot"
        git config --global user.name "Formatting bot"
        git commit -am "Automatic formatting."
        git push
